// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppBlaze.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// fastLogisticModel
Rcpp::List fastLogisticModel(Rcpp::NumericMatrix X_, Rcpp::NumericVector y_);
RcppExport SEXP _RcppLbfgsBlaze_fastLogisticModel(SEXP X_SEXP, SEXP y_SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type X_(X_SEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type y_(y_SEXP);
    rcpp_result_gen = Rcpp::wrap(fastLogisticModel(X_, y_));
    return rcpp_result_gen;
END_RCPP
}
